// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `aws_config_path`, `aws_credentials_path`, `check_aws_cli`, `ensure_aws_dir`, `home_dir`, `normalize_config_profile_name`, `probe_subcommand`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Detect which AWS CLI auth subcommands the installed CLI supports.
/// Each probe has a 3-second timeout to prevent hanging on CLI help pages.
Future<List<String>> getAwsCliCapabilities() =>
    RustLib.instance.api.crateApiAwsProfilesGetAwsCliCapabilities();

/// Returns diagnostics about the AWS CLI environment and profile files.
/// Never returns secret values, only paths, existence, and metadata.
/// Subprocess probes have a 3-second timeout.
Future<AwsDiagnostics> getAwsDiagnostics() =>
    RustLib.instance.api.crateApiAwsProfilesGetAwsDiagnostics();

/// List all local AWS profiles, respecting AWS_CONFIG_FILE and
/// AWS_SHARED_CREDENTIALS_FILE environment variables.
Future<List<AwsProfile>> listLocalAwsProfiles() =>
    RustLib.instance.api.crateApiAwsProfilesListLocalAwsProfiles();

/// Authenticate a non-SSO profile via `aws login --profile <name>`.
Future<String> awsLogin({required String profileName}) =>
    RustLib.instance.api.crateApiAwsProfilesAwsLogin(profileName: profileName);

/// Authenticate an SSO profile via `aws sso login --profile <name>`.
Future<String> ssoLogin({required String profileName}) =>
    RustLib.instance.api.crateApiAwsProfilesSsoLogin(profileName: profileName);

/// Check whether the given profile has valid (non-expired) credentials.
Future<bool> checkProfileCredentials({required String profileName}) => RustLib
    .instance
    .api
    .crateApiAwsProfilesCheckProfileCredentials(profileName: profileName);

/// Add an SSO profile by writing to ~/.aws/config.
Future<void> addSsoProfile({
  required String name,
  required String ssoSession,
  required String ssoStartUrl,
  required String ssoRegion,
  required String ssoAccountId,
  required String ssoRoleName,
}) => RustLib.instance.api.crateApiAwsProfilesAddSsoProfile(
  name: name,
  ssoSession: ssoSession,
  ssoStartUrl: ssoStartUrl,
  ssoRegion: ssoRegion,
  ssoAccountId: ssoAccountId,
  ssoRoleName: ssoRoleName,
);

/// Delete a profile from both credential files.
Future<void> deleteProfile({required String name}) =>
    RustLib.instance.api.crateApiAwsProfilesDeleteProfile(name: name);

/// Diagnostics to help debug profile discovery and CLI setup.
class AwsDiagnostics {
  final String configPath;
  final String credentialsPath;
  final bool configExists;
  final bool credentialsExists;
  final List<String> capabilities;
  final int profileCount;
  final List<String> errors;

  const AwsDiagnostics({
    required this.configPath,
    required this.credentialsPath,
    required this.configExists,
    required this.credentialsExists,
    required this.capabilities,
    required this.profileCount,
    required this.errors,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^
      credentialsPath.hashCode ^
      configExists.hashCode ^
      credentialsExists.hashCode ^
      capabilities.hashCode ^
      profileCount.hashCode ^
      errors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AwsDiagnostics &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          credentialsPath == other.credentialsPath &&
          configExists == other.configExists &&
          credentialsExists == other.credentialsExists &&
          capabilities == other.capabilities &&
          profileCount == other.profileCount &&
          errors == other.errors;
}

/// Represents a discovered AWS profile.
class AwsProfile {
  final String name;

  /// One of: "sso", "role", "credential_source", "static", "short_term"
  final String kind;

  const AwsProfile({required this.name, required this.kind});

  @override
  int get hashCode => name.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AwsProfile &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          kind == other.kind;
}
