// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `is_leap`, `log_error`, `log_info`, `log_warn`, `now_iso`, `push`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Return all buffered dev log entries (newest first).
Future<List<DevLogEntry>> getRecentDevLogs() =>
    RustLib.instance.api.crateApiDevLogsGetRecentDevLogs();

/// Clear all buffered dev log entries.
Future<void> clearDevLogs() =>
    RustLib.instance.api.crateApiDevLogsClearDevLogs();

class DevLogEntry {
  final String timestamp;
  final String level;
  final String scope;
  final String message;

  const DevLogEntry({
    required this.timestamp,
    required this.level,
    required this.scope,
    required this.message,
  });

  @override
  int get hashCode =>
      timestamp.hashCode ^ level.hashCode ^ scope.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DevLogEntry &&
          runtimeType == other.runtimeType &&
          timestamp == other.timestamp &&
          level == other.level &&
          scope == other.scope &&
          message == other.message;
}
