// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `attr_map_to_json_string`, `attr_value_kind`, `attr_value_to_json`, `build_ddb_client`, `build_filter_expression_parts`, `filter_value_to_attr_value`, `json_str_to_attr_map`, `json_val_to_attr_value`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FilterExpressionParts`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

Future<List<String>> listTables({
  required String profile,
  String? regionOverride,
  String? endpointOverride,
}) => RustLib.instance.api.crateApiDynamodbListTables(
  profile: profile,
  regionOverride: regionOverride,
  endpointOverride: endpointOverride,
);

Future<TableSummary> describeTable({
  required String profile,
  String? regionOverride,
  String? endpointOverride,
  required String tableName,
}) => RustLib.instance.api.crateApiDynamodbDescribeTable(
  profile: profile,
  regionOverride: regionOverride,
  endpointOverride: endpointOverride,
  tableName: tableName,
);

Future<ItemsPageResult> scanItems({
  required String profile,
  String? regionOverride,
  String? endpointOverride,
  required String tableName,
  int? limit,
  String? exclusiveStartKeyJson,
  List<FilterClause>? filters,
}) => RustLib.instance.api.crateApiDynamodbScanItems(
  profile: profile,
  regionOverride: regionOverride,
  endpointOverride: endpointOverride,
  tableName: tableName,
  limit: limit,
  exclusiveStartKeyJson: exclusiveStartKeyJson,
  filters: filters,
);

Future<ItemsPageResult> queryItems({
  required String profile,
  String? regionOverride,
  String? endpointOverride,
  required String tableName,
  required String pkName,
  required String pkValue,
  int? limit,
  String? exclusiveStartKeyJson,
  List<FilterClause>? filters,
}) => RustLib.instance.api.crateApiDynamodbQueryItems(
  profile: profile,
  regionOverride: regionOverride,
  endpointOverride: endpointOverride,
  tableName: tableName,
  pkName: pkName,
  pkValue: pkValue,
  limit: limit,
  exclusiveStartKeyJson: exclusiveStartKeyJson,
  filters: filters,
);

Future<void> putItem({
  required String profile,
  String? regionOverride,
  String? endpointOverride,
  required String tableName,
  required String itemJson,
}) => RustLib.instance.api.crateApiDynamodbPutItem(
  profile: profile,
  regionOverride: regionOverride,
  endpointOverride: endpointOverride,
  tableName: tableName,
  itemJson: itemJson,
);

Future<void> putItemCreateOnly({
  required String profile,
  String? regionOverride,
  String? endpointOverride,
  required String tableName,
  required String itemJson,
  required String pkName,
  String? skName,
}) => RustLib.instance.api.crateApiDynamodbPutItemCreateOnly(
  profile: profile,
  regionOverride: regionOverride,
  endpointOverride: endpointOverride,
  tableName: tableName,
  itemJson: itemJson,
  pkName: pkName,
  skName: skName,
);

Future<void> putItemUpdateOnly({
  required String profile,
  String? regionOverride,
  String? endpointOverride,
  required String tableName,
  required String itemJson,
  required String pkName,
  String? skName,
}) => RustLib.instance.api.crateApiDynamodbPutItemUpdateOnly(
  profile: profile,
  regionOverride: regionOverride,
  endpointOverride: endpointOverride,
  tableName: tableName,
  itemJson: itemJson,
  pkName: pkName,
  skName: skName,
);

Future<void> deleteItem({
  required String profile,
  String? regionOverride,
  String? endpointOverride,
  required String tableName,
  required String keyJson,
}) => RustLib.instance.api.crateApiDynamodbDeleteItem(
  profile: profile,
  regionOverride: regionOverride,
  endpointOverride: endpointOverride,
  tableName: tableName,
  keyJson: keyJson,
);

Future<List<AttributeHint>> listTableAttributes({
  required String profile,
  String? regionOverride,
  String? endpointOverride,
  required String tableName,
  int? sampleLimit,
}) => RustLib.instance.api.crateApiDynamodbListTableAttributes(
  profile: profile,
  regionOverride: regionOverride,
  endpointOverride: endpointOverride,
  tableName: tableName,
  sampleLimit: sampleLimit,
);

class AttributeHint {
  final String name;
  final List<String> types;

  const AttributeHint({required this.name, required this.types});

  @override
  int get hashCode => name.hashCode ^ types.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttributeHint &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          types == other.types;
}

class FilterClause {
  final String attribute;
  final String condition;
  final String valueType;
  final String? value;
  final String? value2;

  const FilterClause({
    required this.attribute,
    required this.condition,
    required this.valueType,
    this.value,
    this.value2,
  });

  @override
  int get hashCode =>
      attribute.hashCode ^
      condition.hashCode ^
      valueType.hashCode ^
      value.hashCode ^
      value2.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FilterClause &&
          runtimeType == other.runtimeType &&
          attribute == other.attribute &&
          condition == other.condition &&
          valueType == other.valueType &&
          value == other.value &&
          value2 == other.value2;
}

class ItemsPageResult {
  /// Each item serialised as a JSON string.
  final List<String> itemsJson;

  /// Optional last-evaluated-key as a JSON string, or null.
  final String? lastEvaluatedKeyJson;

  const ItemsPageResult({required this.itemsJson, this.lastEvaluatedKeyJson});

  @override
  int get hashCode => itemsJson.hashCode ^ lastEvaluatedKeyJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ItemsPageResult &&
          runtimeType == other.runtimeType &&
          itemsJson == other.itemsJson &&
          lastEvaluatedKeyJson == other.lastEvaluatedKeyJson;
}

class TableSummary {
  final String name;
  final String status;
  final String? arn;
  final PlatformInt64? itemCount;
  final PlatformInt64? tableSizeBytes;
  final String? billingMode;
  final String? pk;
  final String? sk;
  final List<String> gsis;
  final List<String> lsis;
  final String? streamSpec;

  const TableSummary({
    required this.name,
    required this.status,
    this.arn,
    this.itemCount,
    this.tableSizeBytes,
    this.billingMode,
    this.pk,
    this.sk,
    required this.gsis,
    required this.lsis,
    this.streamSpec,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      status.hashCode ^
      arn.hashCode ^
      itemCount.hashCode ^
      tableSizeBytes.hashCode ^
      billingMode.hashCode ^
      pk.hashCode ^
      sk.hashCode ^
      gsis.hashCode ^
      lsis.hashCode ^
      streamSpec.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TableSummary &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          status == other.status &&
          arn == other.arn &&
          itemCount == other.itemCount &&
          tableSizeBytes == other.tableSizeBytes &&
          billingMode == other.billingMode &&
          pk == other.pk &&
          sk == other.sk &&
          gsis == other.gsis &&
          lsis == other.lsis &&
          streamSpec == other.streamSpec;
}
